### ISSUE TITLE
Interpolated values are concat with neighbor text nodes

### ISSUE THREAD

**Issue by jmas** [tbranyen/transform-tagged-diffhtml#5]
**Problem**
When we try to insert diffhtml element and neighbor is text node as result we get concatenated string.

**Example**
```js
function createFirst () {
    return html`
    <div>
        Text node
        ${createSecond()}
    </div>`;
}
function createSecond () {
    return html`<div>second</div>`;
}
```

**Expectation**
I waiting for tree of diffhtml elements like:
```html
<div>
    Text node
    <div>second</div>
</div>
```

**Actual result**
It just concat result of text node and `createSecond()` call.
```html
<div>
    Text node [Object]
</div>
```

**Comment by tbranyen** [comment]
Reproduced in a unit test, fix forthcoming.

**Comment by tbranyen** [comment]
A-ha, found the offending code:

``` javascript
            else if (value.indexOf(symbol) > -1) {
              args.push(createElement, [
                t.stringLiteral('#text'),
                t.nullLiteral(),
                makeConcatExpr(value, supplemental.children)
              ]);

              isDynamic = true;
            }
```

This code detects if there is a token in the string block, if there is, it attempts to split the text from dynamic. The problem here is that it assumes you're only working within a text node, and not necessarily a mix of types.

**Comment by tbranyen** [comment]
Hey @jmas pushed up a fix, wanna give it a go?

**Comment by jmas** [comment]
@tbranyen Yep, please. I just tested in fork - it working for me.

**Comment by tbranyen** [comment]
Okay great I'll merge and tag a new release.

**Comment by tbranyen** [comment]
I pushed out 1.0.0-rc.4 should be installable now.

**Comment by jmas** [comment]
@tbranyen Maybe `npm` it takes release from Releases? Still can't see it.

**Comment by tbranyen** [comment]
I think I accidentally published it to our internal company's npm >_>.... whoops. Sorry it should be public now ^_^

**Comment by jmas** [comment]
@tbranyen Thanks! Successfully released and delivered.
